### PR TITLE
Add Support For Brainpool Curves

### PR DESCRIPTION
**Pull request by billyb2**
Since at the moment, sslcrypto only supports NIST curves (which may have purposeful vulnerabilities put in by the NSA), I added support for Brainpool curves using RFC 5639 as a reference, using the regular curve (not twisted).

### CODE REVIEW

**Comment by imachug** [comment]
The NIDs (the first integers in the tuples) are from OpenSSL source code. Can you please use the IDs from here: https://boringssl.googlesource.com/boringssl/+/HEAD/include/openssl/nid.h#4076

**Comment by billyb2** [comment]
Just fixed it @imachug. Out of curiosity, is this repo still in active development on Github? I've noticed there's a Gitlab repo as well.

**Comment by imachug** [comment]
> Out of curiosity, is this repo still in active development on Github? I've noticed there's a Gitlab repo as well.

It's not in active development anywhere, not because I abandoned the project but because I don't need anything else for my usecases. The GitHub and GitLab repos are mirrored, BTW, so you can contribute to any of them if you want to, but I check GitHub notifications more often.

**Comment by imachug** [comment]
Please ignore the failing checks, I'm just making experiments on GitHub Actions. Thanks for the contribution, merging!

**Comment by billyb2** [comment]
Oh okay, that's great. Does the PR look good by the way?

**Comment by imachug** [comment]
> Do you think that there could be anyway I could become a partial maintainer in some way? There are many changed I'd like to make to the repo, like OpenPGP compliance as an option, verifying signed messages with recoverable public keys, etc. If not I completely understand, and will continue making PR's.

That would be awesome! I believe in your good intentions so I've added you as a collaborator to this repository. Let's see how it goes.

**Comment by billyb2** [comment]
Thank you so much! This honestly makes me very happy! Would you mind if I quickly change the version number to 5.4?

**Comment by imachug** [comment]
Yeah, feel free to do that.

**Comment by billyb2** [comment]
Thank you again :)

**Pull request merged**
