### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by binarypunk**
Please include your full legal name in the copyright notice.

### CODE REVIEW

**Comment by binarypunk** [comment]
@imachug can you state your full and legal name in the copyright notice? Searching for "Ivanq" in search engines brings up "Ivana Trump", I have doubt that you have any connection to the Trump family.

**Comment by imachug** [comment]
Done.

**Comment by binarypunk** [comment]
:+1:

**Comment by binarypunk** [comment]
@imachug You should be proud that you live in Russia! I wish I can live there! You born in 1996? :rofl: You are a great guy and intelligent! I think you can do more without the Hungarian brigade. :confused: What is your use case of ZeroNet may I ask?

**Comment by binarypunk** [comment]
https://en.wikipedia.org/wiki/Ivan_Khutorskoy :sob:

**Pull request closed without merging**
